services:
  postgres:
    image: postgres:17-alpine
    container_name: mediclick-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: mediclick
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mediclick
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
